module.exports = {
  up: (queryInterface) => queryInterface.bulkInsert(
    'states',
    [
      {
        id: 1,
        country_id: 1,
        name: 'ACRE',
        initials: 'AC',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        country_id: 1,
        name: 'ALAGOAS',
        initials: 'AL',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        country_id: 1,
        name: 'AMAZONAS',
        initials: 'AM',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        country_id: 1,
        name: 'AMAPA',
        initials: 'AP',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 5,
        country_id: 1,
        name: 'BAHIA',
        initials: 'BA',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 6,
        country_id: 1,
        name: 'CEARA',
        initials: 'CE',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 7,
        country_id: 1,
        name: 'DISTRITO FEDERAL',
        initials: 'DF',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 8,
        country_id: 1,
        name: 'ESPIRITO SANTO',
        initials: 'ES',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 9,
        country_id: 1,
        name: 'GOIAS',
        initials: 'GO',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 10,
        country_id: 1,
        name: 'MARANHAO',
        initials: 'MA',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 11,
        country_id: 1,
        name: 'MINAS GERAIS',
        initials: 'MG',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 12,
        country_id: 1,
        name: 'MATO GROSSO DO SUL',
        initials: 'MS',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 13,
        country_id: 1,
        name: 'MATO GROSSO',
        initials: 'MT',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 14,
        country_id: 1,
        name: 'PARA',
        initials: 'PA',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 15,
        country_id: 1,
        name: 'PARAIBA',
        initials: 'PB',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 16,
        country_id: 1,
        name: 'PERNANBUCO',
        initials: 'PE',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 17,
        country_id: 1,
        name: 'PIAUI',
        initials: 'PI',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 18,
        country_id: 1,
        name: 'PARANA',
        initials: 'PR',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 19,
        country_id: 1,
        name: 'RIO DE JANEIRO',
        initials: 'RJ',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 20,
        country_id: 1,
        name: 'RIO GRANDE DO NORTE',
        initials: 'RN',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 21,
        country_id: 1,
        name: 'RONDONIA',
        initials: 'RO',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 22,
        country_id: 1,
        name: 'RORAIMA',
        initials: 'RR',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 23,
        country_id: 1,
        name: 'RIO GRANDE DO SUL',
        initials: 'RS',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 24,
        country_id: 1,
        name: 'SANTA CATARINA',
        initials: 'SC',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 25,
        country_id: 1,
        name: 'SERGIPE',
        initials: 'SE',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 26,
        country_id: 1,
        name: 'SAO PAULO',
        initials: 'SP',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 27,
        country_id: 1,
        name: 'TOCANTINS',
        initials: 'TO',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],

    {},
  ),

  down: (queryInterface) => queryInterface.bulkDelete('states', null, {}),
};
